def compose_final_document(rendered_text: str) -> str:
    """
    Composer bot simply wraps the rendered text into final form.
    """
    header = "SYNTHETIC MEDICAL RECORD – GENERATED BY MEDIEXPLAIN\n\n"
    footer = "\n\nEND OF REPORT\n"
    return header + rendered_text + footer
